name: CD - Deploy Frontend

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build production
        run: npm run build

      - name: Zip dist folder
        run: zip -r dist.zip dist/

      - name: Upload artifact (optional debug)
        uses: actions/upload-artifact@v4
        with:
          name: dist-zip
          path: dist.zip

      - name: Add SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/lottuschave.pem
          chmod 600 ~/.ssh/lottuschave.pem

      - name: Copy dist.zip to EC2 PUBLIC
        run: |
          scp -o StrictHostKeyChecking=no -i ~/.ssh/deploy_key dist.zip \
            ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST_PUBLIC }}:/home/${{ secrets.EC2_USER }}/dist.zip

      - name: From PUBLIC â†’ send dist.zip to FRONT 1 and FRONT 2
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/deploy_key ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST_PUBLIC }} "
          for host in ${{ secrets.FRONT_PRIV1 }} ${{ secrets.FRONT_PRIV2 }}; do
          echo 'Enviando para' \$host '...'
          scp -i /home/ubuntu/parChaves/lottuschave.pem -o StrictHostKeyChecking=no dist.zip ubuntu@\$host:/home/ubuntu/dist.zip
          done
          "



      - name: Mover dist.zip para /var/www/html em cada FRONT
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/deploy_key ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST_PUBLIC }} "
            set -e
            for host in ${{ secrets.FRONT_PRIV1 }} ${{ secrets.FRONT_PRIV2 }}; do
              echo 'Movendo dist.zip em:' \$host
              ssh -i ~/.ssh/lottuschave.pem ubuntu@\$host '
                sudo mkdir -p /var/www/html
                sudo mv ~/dist.zip /var/www/html/
              '
            done
          "
