name: CD - Deploy Frontend

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build production
        run: npm run build

      - name: Zip dist folder
        run: zip -r dist.zip dist/

      - name: Add SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/lottuschave.pem
          chmod 600 ~/.ssh/lottuschave.pem

      # ==========================================================
      # 1) ENVIAR dist.zip PARA A EC2 PUBLICA
      # ==========================================================
      - name: Enviar dist.zip para EC2 PUBLICA
        run: |
          scp -o StrictHostKeyChecking=no -i ~/.ssh/lottuschave.pem dist.zip \
            ubuntu@${{ secrets.EC2_HOST_PUBLIC }}:/home/ubuntu/dist.zip

      # ==========================================================
      # 2) DA PUBLICA → ENVIAR dist.zip PARA AS EC2 PRIVADAS
      # ==========================================================
      - name: PUBLICA → enviar para FRONT 1 e FRONT 2
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/lottuschave.pem ubuntu@${{ secrets.EC2_HOST_PUBLIC }} "
            for host in ${{ secrets.FRONT_PRIV1 }} ${{ secrets.FRONT_PRIV2 }}; do
              echo 'Enviando para' \$host '...'
              scp -o StrictHostKeyChecking=no dist.zip ubuntu@\$host:/home/ubuntu/dist.zip
            done
          "

      # ==========================================================
      # 3) MOVER dist.zip PARA /var/www/html NAS PRIVADAS
      # ==========================================================
      - name: Mover dist.zip para /var/www/html
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/lottuschave.pem ubuntu@${{ secrets.EC2_HOST_PUBLIC }} "
            for host in ${{ secrets.FRONT_PRIV1 }} ${{ secrets.FRONT_PRIV2 }}; do
              echo 'Movendo dist.zip em:' \$host
              ssh -o StrictHostKeyChecking=no ubuntu@\$host '
                sudo mkdir -p /var/www/html &&
                sudo mv ~/dist.zip /var/www/html/
              '
            done
          "
